name: Build rowing timing web application
run-name: Building front- and backend for the rowing timing application
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build -t 127.0.0.1:5000/rowing-timing-backend:latest .
      - run: docker push 127.0.0.1:5000/rowing-timing-backend:latest
